version: "3.8"
services:
  mongodb-server:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - /data/db
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    depends_on:
      - api
      - client
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '3009:3009'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ORIGIN=http://localhost:3050
      - PORT=3009
      - SECRET=secret
      - DB=userData
      - MONGO_URL=mongodb+srv://root:root@cluster0.oz4c0kw.mongodb.net/?retryWrites=true&w=majority
  client:
    build:
      dockerfile: Dockerfile
      context: ./client   
    volumes:  
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0
      - REACT_APP_BASE_URL=http://localhost:3050/api/v1
      - REACT_APP_BACKEND_URL=http://localhost:3009