version: '3'
services:
  client:
    image: "tarak99/multi-client"
    mem_limit: 128m
    hostname: client
    environment:
    - WDS_SOCKET_PORT=$WDS_SOCKET_PORT
    - REACT_APP_BASE_URL=$REACT_APP_BASE_URL
    - REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL
  server:
    image: "tarak99/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - ORIGIN=$ORIGIN
      - PORT=$PORT
      - SECRET=$SECRET
      - DB=$DB
      - MONGO_URL=$MONGO_URL
    ports:
      -"3009":"3009"
  nginx:
    image: "tarak99/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
    